### ISSUE TITLE
Error when calling two Play functions in a row

### ISSUE THREAD

**Issue by irevenko** [faiface/beep#112]
OS: ```Linux Manjaro```

I want to call ```PlayBeepLong``` function multiple times in my code, but it does not work. What am i doing wrong?
```go
package main

func PlayBeepLong(count int) {
	f, err := os.Open("beep_long.wav")
	if err != nil {
		log.Fatal(err)
	}

	streamer, format, err := wav.Decode(f)
	if err != nil {
		log.Fatal(err)
	}
	defer streamer.Close()

	speaker.Init(format.SampleRate, format.SampleRate.N(time.Second/10))
	
	done := make(chan bool)

	for i := 0; i < count; i++ {
		speaker.Play(beep.Seq(streamer, beep.Callback(func() {
			done <- true
		})))

		<-done
		streamer.Seek(0)
	}
}

func main() { 
	PlayBeepLong(2)
	PlayBeepLong(2)
}


```
Error:
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18a5 pc=0x7fb11b0a80fa]

runtime stack:
runtime.throw(0x66a95e, 0x2a)
        /usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:726 +0x4ac

goroutine 6 [syscall]:
runtime.cgocall(0x5a2050, 0xc000048e70, 0xc000048e00)
        /usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc000048e40 sp=0xc000048e08 pc=0x48365b
github.com/hajimehoshi/oto._Cfunc_snd_pcm_drop(0x1869240, 0xc000000000)
        _cgo_gotypes.go:134 +0x49 fp=0xc000048e70 sp=0xc000048e40 pc=0x575969
github.com/hajimehoshi/oto.(*driver).Close.func1(0xc000060040, 0xc0002fe000)
        /home/irevenko/go/src/github.com/hajimehoshi/oto/driver_linux.go:177 +0x59 fp=0xc000048ea8 sp=0xc000048e70 pc=0x576d79
github.com/hajimehoshi/oto.(*driver).Close(0xc000060040, 0x66d500, 0x1)
        /home/irevenko/go/src/github.com/hajimehoshi/oto/driver_linux.go:177 +0x2f fp=0xc000048ed0 sp=0xc000048ea8 pc=0x5766af
github.com/hajimehoshi/oto.(*driverWriter).Close(0xc000076660, 0x0, 0x0)
        /home/irevenko/go/src/github.com/hajimehoshi/oto/context.go:170 +0xb5 fp=0xc000048f18 sp=0xc000048ed0 pc=0x574ef5
github.com/hajimehoshi/oto.(*Context).Close(0xc00000e160, 0xc000076660, 0x68d660)
        /home/irevenko/go/src/github.com/hajimehoshi/oto/context.go:106 +0x7b fp=0xc000048f68 sp=0xc000048f18 pc=0x57497b
github.com/hajimehoshi/oto.NewContext.func1(0xc00000e160)
        /home/irevenko/go/src/github.com/hajimehoshi/oto/context.go:89 +0xa5 fp=0xc000048fd8 sp=0xc000048f68 pc=0x576805
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000048fe0 sp=0xc000048fd8 pc=0x4e76a1
created by github.com/hajimehoshi/oto.NewContext
        /home/irevenko/go/src/github.com/hajimehoshi/oto/context.go:84 +0x269

goroutine 1 [chan receive]:
_/home/irevenko/Code/morse2sound/sound.PlayBeepLong(0x2)
        /home/irevenko/Code/morse2sound/sound/sound.go:64 +0x257
main.main()
        /home/irevenko/Code/morse2sound/main.go:14 +0xc5

goroutine 8 [syscall]:
github.com/hajimehoshi/oto._Cfunc_snd_pcm_writei(0x7fb0e40069c0, 0xc000407800, 0x5be, 0x0)
        _cgo_gotypes.go:176 +0x4e
github.com/hajimehoshi/oto.(*driver).TryWrite.func1(0xc0000600c0, 0xc0002f6000)
        /home/irevenko/go/src/github.com/hajimehoshi/oto/driver_linux.go:158 +0xda
github.com/hajimehoshi/oto.(*driver).TryWrite(0xc0000600c0, 0xc0002f60c8, 0x38, 0x8000, 0x5d0f80, 0xc000076750, 0xc0000788f0)
        /home/irevenko/go/src/github.com/hajimehoshi/oto/driver_linux.go:158 +0x1d8
github.com/hajimehoshi/oto.(*driverWriter).Write(0xc000076720, 0xc0002f6000, 0x100, 0x8000, 0x0, 0x0, 0x0)
        /home/irevenko/go/src/github.com/hajimehoshi/oto/context.go:144 +0x11f
io.copyBuffer(0x68d640, 0xc000076720, 0x68d660, 0xc000060100, 0xc0002f6000, 0x8000, 0x8000, 0x0, 0xc00003cfd0, 0x579045)
        /usr/local/go/src/io/io.go:411 +0x206
io.Copy(...)
        /usr/local/go/src/io/io.go:368
github.com/hajimehoshi/oto.NewContext.func1(0xc00031c9e0)
        /home/irevenko/go/src/github.com/hajimehoshi/oto/context.go:85 +0x69
created by github.com/hajimehoshi/oto.NewContext
        /home/irevenko/go/src/github.com/hajimehoshi/oto/context.go:84 +0x269

goroutine 9 [select]:
io.(*pipe).Write(0xc000062420, 0xc000157f30, 0x2db8, 0x2db8, 0x1730, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:94 +0x1e5
io.(*PipeWriter).Write(0xc000010060, 0xc000156800, 0x44e8, 0x44e8, 0x13a, 0x1, 0x13a)
        /usr/local/go/src/io/pipe.go:163 +0x4c
github.com/hajimehoshi/oto.(*Player).Write(0xc000076780, 0xc000156800, 0x44e8, 0x44e8, 0x113a, 0x1, 0x0)
        /home/irevenko/go/src/github.com/hajimehoshi/oto/player.go:66 +0x96
github.com/faiface/beep/speaker.update()
        /home/irevenko/go/src/github.com/faiface/beep/speaker/speaker.go:129 +0x1ae
github.com/faiface/beep/speaker.Init.func1()
        /home/irevenko/go/src/github.com/faiface/beep/speaker/speaker.go:52 +0x25
created by github.com/faiface/beep/speaker.Init
        /home/irevenko/go/src/github.com/faiface/beep/speaker/speaker.go:48 +0x1f3
exit status 2
```

**Comment by irevenko** [comment]
Figured it out.
It was ```oto library``` problem, i just need to create a context and player outside of ```play``` function

```go
package main

import (
	"io/ioutil"
	"log"
	"time"

	"github.com/hajimehoshi/oto"
	"github.com/tosone/minimp3"
)

func read() (decoder *minimp3.Decoder, audioData []byte) {
	file, err := ioutil.ReadFile("beep-07.mp3")
	if err != nil {
		log.Fatal(file)
	}

	var dec *minimp3.Decoder
	var data []byte
	dec, data, _ = minimp3.DecodeFull(file)

	return dec, data
}

func play(data []byte, dec *minimp3.Decoder, p *oto.Player) {
	p.Write(data)

	<-time.After(time.Second)

	dec.Close()
}

func main() {
	decoder, data := read()

	var context *oto.Context
	context, _= oto.NewContext(decoder.SampleRate, decoder.Channels, 2, 1024)
	player := context.NewPlayer()


	play(data, decoder, player)
	play(data, decoder, player)
}
```
